//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNang_TaiKhoan
    {
        public string UserName { get; set; }
        public string Menu { get; set; }
        public Nullable<System.DateTime> SetTime { get; set; }
        public Nullable<bool> QuyenThem { get; set; }
        public Nullable<bool> QuyenSua { get; set; }
        public Nullable<bool> QuyenXoa { get; set; }
        public Nullable<bool> Cam { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
