//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemHP
    {
        public string MaSV { get; set; }
        public string MaMonHP { get; set; }
        public Nullable<double> ChuyenCan { get; set; }
        public Nullable<double> GiuaKi { get; set; }
        public Nullable<double> DiemLan1 { get; set; }
        public Nullable<double> DiemLan2 { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual MonHP MonHP { get; set; }
    }
}
