//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHP()
        {
            this.DiemHP = new HashSet<DiemHP>();
            this.GV_PhanCong = new HashSet<GV_PhanCong>();
        }
    
        public short ID { get; set; }
        public string MaMonHP { get; set; }
        public string TenMonHP { get; set; }
        public Nullable<byte> SoTin { get; set; }
        public Nullable<byte> TietLT { get; set; }
        public Nullable<byte> TietTH { get; set; }
        public string MaHK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemHP> DiemHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_PhanCong> GV_PhanCong { get; set; }
        public virtual HocKy HocKy { get; set; }
    }
}
