//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiDiemEntities : DbContext
    {
        public QuanLiDiemEntities()
            : base("name=QuanLiDiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangNhap> DangNhap { get; set; }
        public virtual DbSet<DiemHP> DiemHP { get; set; }
        public virtual DbSet<GiaoVien> GiaoVien { get; set; }
        public virtual DbSet<GiaoVien_HinhAnh> GiaoVien_HinhAnh { get; set; }
        public virtual DbSet<HeDaoTao> HeDaoTao { get; set; }
        public virtual DbSet<HocKy> HocKy { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<MonHP> MonHP { get; set; }
        public virtual DbSet<PhanCong> PhanCong { get; set; }
        public virtual DbSet<SinhVien> SinhVien { get; set; }
        public virtual DbSet<SinhVien_HinhAnh> SinhVien_HinhAnh { get; set; }
        public virtual DbSet<TinhTrang> TinhTrang { get; set; }
        public virtual DbSet<ThongTin> ThongTin { get; set; }
        public virtual DbSet<GV_PhanCong> GV_PhanCong { get; set; }
    
        public virtual ObjectResult<BangDiemHP_Result> BangDiemHP(string maLop, string maMonHP)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BangDiemHP_Result>("BangDiemHP", maLopParameter, maMonHPParameter);
        }
    
        public virtual int DiemHPDelete(string maSV, string maMonHP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemHPDelete", maSVParameter, maMonHPParameter);
        }
    
        public virtual int DiemHPInsert(string maSV, string maMonHP, Nullable<double> chuyenCan, Nullable<double> giuaKi, Nullable<double> diemLan1, string ghiChu)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            var chuyenCanParameter = chuyenCan.HasValue ?
                new ObjectParameter("ChuyenCan", chuyenCan) :
                new ObjectParameter("ChuyenCan", typeof(double));
    
            var giuaKiParameter = giuaKi.HasValue ?
                new ObjectParameter("GiuaKi", giuaKi) :
                new ObjectParameter("GiuaKi", typeof(double));
    
            var diemLan1Parameter = diemLan1.HasValue ?
                new ObjectParameter("DiemLan1", diemLan1) :
                new ObjectParameter("DiemLan1", typeof(double));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemHPInsert", maSVParameter, maMonHPParameter, chuyenCanParameter, giuaKiParameter, diemLan1Parameter, ghiChuParameter);
        }
    
        public virtual int DiemHPInsert_1(string maMonHP, string maSV)
        {
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemHPInsert_1", maMonHPParameter, maSVParameter);
        }
    
        public virtual int DiemHPInsert_2(string maSV, string maMonHP)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemHPInsert_2", maSVParameter, maMonHPParameter);
        }
    
        public virtual ObjectResult<DiemHPSearch_Result> DiemHPSearch(string maMonHP, string maSV)
        {
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DiemHPSearch_Result>("DiemHPSearch", maMonHPParameter, maSVParameter);
        }
    
        public virtual int DiemHPUpdate(string maSV, string maMonHP, Nullable<double> chuyenCan, Nullable<double> giuaKi, Nullable<double> diemLan1, string ghiChu)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            var chuyenCanParameter = chuyenCan.HasValue ?
                new ObjectParameter("ChuyenCan", chuyenCan) :
                new ObjectParameter("ChuyenCan", typeof(double));
    
            var giuaKiParameter = giuaKi.HasValue ?
                new ObjectParameter("GiuaKi", giuaKi) :
                new ObjectParameter("GiuaKi", typeof(double));
    
            var diemLan1Parameter = diemLan1.HasValue ?
                new ObjectParameter("DiemLan1", diemLan1) :
                new ObjectParameter("DiemLan1", typeof(double));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemHPUpdate", maSVParameter, maMonHPParameter, chuyenCanParameter, giuaKiParameter, diemLan1Parameter, ghiChuParameter);
        }
    
        public virtual int DiemLan1Update(Nullable<double> chuyenCan, Nullable<double> giuaKi, Nullable<double> diemLan1, string maSV, string maMonHP)
        {
            var chuyenCanParameter = chuyenCan.HasValue ?
                new ObjectParameter("ChuyenCan", chuyenCan) :
                new ObjectParameter("ChuyenCan", typeof(double));
    
            var giuaKiParameter = giuaKi.HasValue ?
                new ObjectParameter("GiuaKi", giuaKi) :
                new ObjectParameter("GiuaKi", typeof(double));
    
            var diemLan1Parameter = diemLan1.HasValue ?
                new ObjectParameter("DiemLan1", diemLan1) :
                new ObjectParameter("DiemLan1", typeof(double));
    
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiemLan1Update", chuyenCanParameter, giuaKiParameter, diemLan1Parameter, maSVParameter, maMonHPParameter);
        }
    
        public virtual int HeDaoTaoDelete(string maHe)
        {
            var maHeParameter = maHe != null ?
                new ObjectParameter("MaHe", maHe) :
                new ObjectParameter("MaHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HeDaoTaoDelete", maHeParameter);
        }
    
        public virtual int HeDaoTaoInsert(string tenHe)
        {
            var tenHeParameter = tenHe != null ?
                new ObjectParameter("TenHe", tenHe) :
                new ObjectParameter("TenHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HeDaoTaoInsert", tenHeParameter);
        }
    
        public virtual int HeDaoTaoUpdate(string maHe, string tenHe)
        {
            var maHeParameter = maHe != null ?
                new ObjectParameter("MaHe", maHe) :
                new ObjectParameter("MaHe", typeof(string));
    
            var tenHeParameter = tenHe != null ?
                new ObjectParameter("TenHe", tenHe) :
                new ObjectParameter("TenHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HeDaoTaoUpdate", maHeParameter, tenHeParameter);
        }
    
        public virtual ObjectResult<HeSelectALL_Result> HeSelectALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HeSelectALL_Result>("HeSelectALL");
        }
    
        public virtual ObjectResult<HKSelectALL_Result> HKSelectALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HKSelectALL_Result>("HKSelectALL");
        }
    
        public virtual int HocKyDelete(string maHK)
        {
            var maHKParameter = maHK != null ?
                new ObjectParameter("MaHK", maHK) :
                new ObjectParameter("MaHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HocKyDelete", maHKParameter);
        }
    
        public virtual int HocKyInsert(string tenHK)
        {
            var tenHKParameter = tenHK != null ?
                new ObjectParameter("TenHK", tenHK) :
                new ObjectParameter("TenHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HocKyInsert", tenHKParameter);
        }
    
        public virtual int HocKyUpdate(string maHK, string tenHK)
        {
            var maHKParameter = maHK != null ?
                new ObjectParameter("MaHK", maHK) :
                new ObjectParameter("MaHK", typeof(string));
    
            var tenHKParameter = tenHK != null ?
                new ObjectParameter("TenHK", tenHK) :
                new ObjectParameter("TenHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HocKyUpdate", maHKParameter, tenHKParameter);
        }
    
        public virtual int LopDelete(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LopDelete", maLopParameter);
        }
    
        public virtual int LopInsert(string tenLop, string maHe)
        {
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maHeParameter = maHe != null ?
                new ObjectParameter("MaHe", maHe) :
                new ObjectParameter("MaHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LopInsert", tenLopParameter, maHeParameter);
        }
    
        public virtual ObjectResult<LopSelectAll_Result> LopSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LopSelectAll_Result>("LopSelectAll");
        }
    
        public virtual ObjectResult<LopSelectALLByHe_Result> LopSelectALLByHe(string maHe)
        {
            var maHeParameter = maHe != null ?
                new ObjectParameter("MaHe", maHe) :
                new ObjectParameter("MaHe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LopSelectALLByHe_Result>("LopSelectALLByHe", maHeParameter);
        }
    
        public virtual int LopUpdate(string maLop, string tenLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LopUpdate", maLopParameter, tenLopParameter);
        }
    
        public virtual ObjectResult<MonHP_SelectByHK_Result> MonHP_SelectByHK(string maHK)
        {
            var maHKParameter = maHK != null ?
                new ObjectParameter("MaHK", maHK) :
                new ObjectParameter("MaHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonHP_SelectByHK_Result>("MonHP_SelectByHK", maHKParameter);
        }
    
        public virtual int MonHPDelete(string maMonHP)
        {
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MonHPDelete", maMonHPParameter);
        }
    
        public virtual int MonHPInsert(string tenMonHP, Nullable<byte> soTin, Nullable<byte> tietLT, Nullable<byte> tietTH, string maHK)
        {
            var tenMonHPParameter = tenMonHP != null ?
                new ObjectParameter("TenMonHP", tenMonHP) :
                new ObjectParameter("TenMonHP", typeof(string));
    
            var soTinParameter = soTin.HasValue ?
                new ObjectParameter("SoTin", soTin) :
                new ObjectParameter("SoTin", typeof(byte));
    
            var tietLTParameter = tietLT.HasValue ?
                new ObjectParameter("TietLT", tietLT) :
                new ObjectParameter("TietLT", typeof(byte));
    
            var tietTHParameter = tietTH.HasValue ?
                new ObjectParameter("TietTH", tietTH) :
                new ObjectParameter("TietTH", typeof(byte));
    
            var maHKParameter = maHK != null ?
                new ObjectParameter("MaHK", maHK) :
                new ObjectParameter("MaHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MonHPInsert", tenMonHPParameter, soTinParameter, tietLTParameter, tietTHParameter, maHKParameter);
        }
    
        public virtual ObjectResult<MonHPOnlySelect_Result> MonHPOnlySelect(string maMonHP)
        {
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonHPOnlySelect_Result>("MonHPOnlySelect", maMonHPParameter);
        }
    
        public virtual ObjectResult<MonHPSelectAll_Result> MonHPSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonHPSelectAll_Result>("MonHPSelectAll");
        }
    
        public virtual ObjectResult<MonHPSelectBySV_Result> MonHPSelectBySV(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonHPSelectBySV_Result>("MonHPSelectBySV", maSVParameter);
        }
    
        public virtual int MonHPUpdate(string maMonHP, string tenMonHP, Nullable<byte> soTin, Nullable<byte> tietLT, Nullable<byte> tietTH)
        {
            var maMonHPParameter = maMonHP != null ?
                new ObjectParameter("MaMonHP", maMonHP) :
                new ObjectParameter("MaMonHP", typeof(string));
    
            var tenMonHPParameter = tenMonHP != null ?
                new ObjectParameter("TenMonHP", tenMonHP) :
                new ObjectParameter("TenMonHP", typeof(string));
    
            var soTinParameter = soTin.HasValue ?
                new ObjectParameter("SoTin", soTin) :
                new ObjectParameter("SoTin", typeof(byte));
    
            var tietLTParameter = tietLT.HasValue ?
                new ObjectParameter("TietLT", tietLT) :
                new ObjectParameter("TietLT", typeof(byte));
    
            var tietTHParameter = tietTH.HasValue ?
                new ObjectParameter("TietTH", tietTH) :
                new ObjectParameter("TietTH", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MonHPUpdate", maMonHPParameter, tenMonHPParameter, soTinParameter, tietLTParameter, tietTHParameter);
        }
    
        public virtual int SinhVienDelete(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienDelete", maSVParameter);
        }
    
        public virtual ObjectResult<SinhVienHA_SelectALL_Result> SinhVienHA_SelectALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienHA_SelectALL_Result>("SinhVienHA_SelectALL");
        }
    
        public virtual ObjectResult<SinhVienHA_SelectByLop_Result> SinhVienHA_SelectByLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienHA_SelectByLop_Result>("SinhVienHA_SelectByLop", maLopParameter);
        }
    
        public virtual int SinhVienHA_Update(string sV_IMG, byte[] iMG, string fileIMG)
        {
            var sV_IMGParameter = sV_IMG != null ?
                new ObjectParameter("SV_IMG", sV_IMG) :
                new ObjectParameter("SV_IMG", typeof(string));
    
            var iMGParameter = iMG != null ?
                new ObjectParameter("IMG", iMG) :
                new ObjectParameter("IMG", typeof(byte[]));
    
            var fileIMGParameter = fileIMG != null ?
                new ObjectParameter("FileIMG", fileIMG) :
                new ObjectParameter("FileIMG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienHA_Update", sV_IMGParameter, iMGParameter, fileIMGParameter);
        }
    
        public virtual int SinhVienInsert(string hoLot, string ten, Nullable<System.DateTime> ngaySinh, string gioiTinh, string noiSinh, string danToc, string maLop, string maTinhTrang)
        {
            var hoLotParameter = hoLot != null ?
                new ObjectParameter("HoLot", hoLot) :
                new ObjectParameter("HoLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var maTinhTrangParameter = maTinhTrang != null ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienInsert", hoLotParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, noiSinhParameter, danTocParameter, maLopParameter, maTinhTrangParameter);
        }
    
        public virtual ObjectResult<SinhVienSelectAll_Result> SinhVienSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAll_Result>("SinhVienSelectAll");
        }
    
        public virtual ObjectResult<SinhVienSelectAllByID_Result> SinhVienSelectAllByID(string maSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAllByID_Result>("SinhVienSelectAllByID", maSVParameter);
        }
    
        public virtual ObjectResult<SinhVienSelectAllByLop_Result> SinhVienSelectAllByLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAllByLop_Result>("SinhVienSelectAllByLop", maLopParameter);
        }
    
        public virtual ObjectResult<SinhVienSelectAllByLopDetail_Result> SinhVienSelectAllByLopDetail(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAllByLopDetail_Result>("SinhVienSelectAllByLopDetail", maLopParameter);
        }
    
        public virtual ObjectResult<SinhVienSelectAllDetail_Result> SinhVienSelectAllDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAllDetail_Result>("SinhVienSelectAllDetail");
        }
    
        public virtual ObjectResult<SinhVienSelectAllDetail_1_Result> SinhVienSelectAllDetail_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectAllDetail_1_Result>("SinhVienSelectAllDetail_1");
        }
    
        public virtual int SinhVienUpdate(string maSV, string hoLot, string ten, Nullable<System.DateTime> ngaySinh, string gioiTinh, string noiSinh, string danToc)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var hoLotParameter = hoLot != null ?
                new ObjectParameter("HoLot", hoLot) :
                new ObjectParameter("HoLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienUpdate", maSVParameter, hoLotParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, noiSinhParameter, danTocParameter);
        }
    
        public virtual int SinhVienUpdate_1(string maSV, Nullable<System.DateTime> ngaySinh, string gioiTinh, string noiSinh, string danToc)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienUpdate_1", maSVParameter, ngaySinhParameter, gioiTinhParameter, noiSinhParameter, danTocParameter);
        }
    
        public virtual int ThongTinUpdate(string maThongTin, string donViChuQuan, string tenTruong, string tinh, string khoaHoc, string nganhHoc, string chuyenNganh)
        {
            var maThongTinParameter = maThongTin != null ?
                new ObjectParameter("MaThongTin", maThongTin) :
                new ObjectParameter("MaThongTin", typeof(string));
    
            var donViChuQuanParameter = donViChuQuan != null ?
                new ObjectParameter("DonViChuQuan", donViChuQuan) :
                new ObjectParameter("DonViChuQuan", typeof(string));
    
            var tenTruongParameter = tenTruong != null ?
                new ObjectParameter("TenTruong", tenTruong) :
                new ObjectParameter("TenTruong", typeof(string));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var khoaHocParameter = khoaHoc != null ?
                new ObjectParameter("KhoaHoc", khoaHoc) :
                new ObjectParameter("KhoaHoc", typeof(string));
    
            var nganhHocParameter = nganhHoc != null ?
                new ObjectParameter("NganhHoc", nganhHoc) :
                new ObjectParameter("NganhHoc", typeof(string));
    
            var chuyenNganhParameter = chuyenNganh != null ?
                new ObjectParameter("ChuyenNganh", chuyenNganh) :
                new ObjectParameter("ChuyenNganh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThongTinUpdate", maThongTinParameter, donViChuQuanParameter, tenTruongParameter, tinhParameter, khoaHocParameter, nganhHocParameter, chuyenNganhParameter);
        }
    
        public virtual int TinhTrangDelete(string maTinhTrang)
        {
            var maTinhTrangParameter = maTinhTrang != null ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinhTrangDelete", maTinhTrangParameter);
        }
    
        public virtual int TinhTrangInsert(string tinhTrang)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinhTrangInsert", tinhTrangParameter);
        }
    
        public virtual int TinhTrangUpdate(string maTinhTrang, string tinhTrang)
        {
            var maTinhTrangParameter = maTinhTrang != null ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(string));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TinhTrangUpdate", maTinhTrangParameter, tinhTrangParameter);
        }
    
        public virtual int SinhVienInsert_1(string hoLot, string ten, Nullable<System.DateTime> ngaySinh, string gioiTinh, string noiSinh, string danToc, string maLop)
        {
            var hoLotParameter = hoLot != null ?
                new ObjectParameter("HoLot", hoLot) :
                new ObjectParameter("HoLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var noiSinhParameter = noiSinh != null ?
                new ObjectParameter("NoiSinh", noiSinh) :
                new ObjectParameter("NoiSinh", typeof(string));
    
            var danTocParameter = danToc != null ?
                new ObjectParameter("DanToc", danToc) :
                new ObjectParameter("DanToc", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVienInsert_1", hoLotParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, noiSinhParameter, danTocParameter, maLopParameter);
        }
    
        public virtual ObjectResult<SinhVienSelectCheckNew_Result> SinhVienSelectCheckNew(string hoLot, string ten)
        {
            var hoLotParameter = hoLot != null ?
                new ObjectParameter("HoLot", hoLot) :
                new ObjectParameter("HoLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SinhVienSelectCheckNew_Result>("SinhVienSelectCheckNew", hoLotParameter, tenParameter);
        }
    }
}
