//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public short ID { get; set; }
        public string MaThongTin { get; set; }
        public string Tinh { get; set; }
        public string DonViChuQuan { get; set; }
        public string TenTruong { get; set; }
        public string KhoaHoc { get; set; }
        public string NganhHoc { get; set; }
        public string ChuyenNganh { get; set; }
    }
}
